version: '3.3'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-api-node
    ports:
      - "3500:3500"
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
    environment:
      - NODE_ENV=production
      - PORT=3500
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
