name: Build and Push Docker Image

# Controla quando o workflow será executado
on:
  # Aciona o workflow em eventos push, mas apenas na branch main
  push:
    branches: [ "main" ]
  # Permite executar manualmente a partir da aba "Actions" do GitHub
  workflow_dispatch:

# Permissões para o token GITHUB_TOKEN
permissions:
  contents: read

# Um workflow consiste em um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este workflow contém um único job chamado "build"
  build:
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do seu código no runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura o QEMU para que possamos fazer builds multi-plataforma
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Configura o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Faz login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extrai metadados (tags, labels) para Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: prixua/whatsapp-api

      # Constrói e publica a imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max